### ISSUE TITLE
Support for saving files

### ISSUE THREAD

**Issue by badb** [tomusdrw/ethsign#10]
Hi! 
Do you have in plans to add functionality to actually create password protected JSON keyfiles? Function taking as arguments SecretKey, password and path to the file and creating proper keystore file would be extremely useful.

**Comment by tomusdrw** [comment]
See #11 it will be possible to do:
```rust
let secret: SecretKey = ...;
let crypto = secret.to_crypto(password, iterations).unwrap();
let keyfile = keyfile::KeyFile {
 id: "Whataver",
 version: 3,
 crypto,
 address: Some(secret.public().address()),
};

// then since `KeyFile` is Serializable you can do:
let mut file = std::fs::File::create("keyfile.json").unwrap();
serde_json::to_writer_pretty(&mut file, keyfile);

```

**Comment by tworec** [comment]
didn't see this ;) and #11 when implementing #12

**Comment by tworec** [comment]
Above code sample is not valid. Address should be 
> ```rust
> address: Some(Bytes(secret.public().address().to_vec())),
> ``` 

I've created crate [`ethkey`](https://docs.rs/ethkey/0.2.5/ethkey/) which simplifies keystore creation

**Comment by tomusdrw** [comment]
@tworec Great stuff, thanks a lot. I'd welcome a PR to update the readme and cross-reference `ethkey` as higher-level library to manage `KeyFiles`.

**Comment by tworec** [comment]
I was wondering if it will not be too intrusive. I'll make an PR in some spare time ;)
